name: touch_lock
description: A screen touch lock module for Flutter.It is a lock system for children. If you lock the screen, it will not be unlocked without marking the correct number.
version: 0.0.3
author: Behlul Bozal <behlulbozal@gmail.com>
homepage: https://github.com/behlulbozal/touch_lock.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
