name: touch_lock
description: A screen touch lock module for Flutter.
version: 0.0.1
author: Behlul Bozal <behlulbozal@gmail.com>
homepage: https://github.com/behlulbozal/touch_lock.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
